#!/usr/bin/env python3
"""Reference backtest: real public data -> Evidergy core algorithms -> versioned metrics.

Purpose
-------
The 2026-08-08 business plan states plainly that public-dataset backtesting was not
yet complete and no accuracy had been verified. This script closes that specific gap
using data that is public, free, checksummed and reproducible *today*, without
waiting on the written commercial-use permission that DKASC/DKP (sources.json,
tier A, "written_permission_required_before_commercial_training_or_redistribution")
still requires. It is deliberately NOT presented as the Alice Springs pilot: it is a
representative public reference dataset used to demonstrate that the algorithms in
core_models.py behave correctly, are bounded/calibrated, and can be backtested
end-to-end on real (non-synthetic) meter data. That is the literal TRL4 bar in the
PERIscope guidelines: "proof of concept has been validated. Demonstration of
technical feasibility have been shown with representative data."

Data sources (see docs/REFERENCE_DATASET.md for full provenance and licence text)
-----------------------------------------------------------------------------------
1. Open Power System Data - household_data, release 2020-04-15 (CC-BY, ISC Konstanz).
   Real 15-minute cumulative smart-meter readings, 2014-12 to 2019-05.
     - DE_KN_residential4: grid_import, grid_export, pv, plus five submetered
       appliance circuits (dishwasher, freezer, heat_pump, refrigerator,
       washing_machine, ev). ~100% interval coverage in calendar year 2016.
     - DE_KN_industrial2: grid_import, pv, storage_charge, storage_decharge
       (a real behind-the-meter battery). ~68-86% coverage in 2016 -- these are
       genuine gaps in the source file, not injected for the demo.
2. Open-Meteo Historical Weather API (open data, no key required). Hourly
   temperature_2m and shortwave/direct/diffuse radiation for Konstanz, Germany
   (47.6779N, 9.1732E), calendar year 2016.
3. DCCEEW National Greenhouse Accounts Factors 2025, Table 1: Northern Territory
   (Darwin-Katherine Interconnected System) location-based Scope 2 factor,
   0.56 kg CO2-e/kWh. Downloaded directly, no login, from dcceew.gov.au.

What is, and is not, being claimed
-----------------------------------
- Energy balance ("identity" check): grid_import - grid_export + pv is compared
  against itself by construction on residential4 (there is no independent,
  redundantly-metered PCC in this public dataset). This validates that the
  sign-convention / unit-conversion / residual code path reproduces the meter
  physics correctly on real, messy, DST-aware timestamps -- a legitimate TRL4-level
  pipeline check -- and is reported separately from "metering completeness"
  (how much of that identity load the five submeters actually explain), which is
  a genuine, non-circular, real-world statistic.
- Quantile load forecast: trained and backtested on a real target
  (grid_import - grid_export + pv) with a fixed, non-shuffled rolling-origin
  train/validate/test split, real calendar + weather features. Fully real,
  non-circular.
- PV evidence: the weather-adjusted baseline is fit on real irradiance/temperature
  and real PV output. Because this public release carries no labelled outage
  events (unlike the DKASC 2021 "Notes on the Data" the roadmap targets for the
  real pilot), detection recall/false-positive rate are measured by injecting
  synthetic, clearly-logged outage windows into real held-out PV output -- a
  standard fault-injection validation technique, not a claim of real labelled
  incidents.
- BESS evidence: OPSD publishes charge/discharge energy, not an OEM SOC signal.
  An indicative "charge-tracking index" is derived from real charge/discharge
  telemetry using a data-driven capacity estimate. The consistency-rule detection
  logic is then validated the same way as PV: synthetic sign/telemetry corruption
  injected into real intervals, recall and false-positive rate measured against
  clean real intervals.
- Scope 2: real monthly grid-import kWh (residential4, 2016) x the real,
  published NT (DKIS) location-based factor. 100% recompute consistency is the
  documented BP acceptance target for this check (deterministic multiplication),
  not a statistical claim.

Outputs
-------
data_processed/reference_2016/backtest_report.json   -- versioned metrics + provenance
data_processed/reference_2016/*.csv                  -- normalised extracts for audit
../lib/reference-dataset.ts (generated by generate_reference_ts.py, not this file)
"""
from __future__ import annotations

import hashlib
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from core_models import (  # noqa: E402
    QuantileForecast,
    apply_interval_delta,
    bess_consistency,
    conformal_interval_delta,
    energy_balance,
    forecast_metrics,
    pv_underperformance,
    quality_flags,
    scope2_ledger,
)

RAW = Path(__file__).parent.parent / "data_raw"
OUT = Path(__file__).parent.parent / "data_processed" / "reference_2016"
OUT.mkdir(parents=True, exist_ok=True)

DATA_VERSION = "opsd-household-2020-04-15+open-meteo-archive+nga-factors-2025"
MODEL_VERSION = "REF-BACKTEST-v1.0.0"
RNG = np.random.default_rng(20260808)  # fixed seed: reproducible fault injection

KONSTANZ_LAT, KONSTANZ_LON = 47.6779, 9.1732
NT_DKIS_SCOPE2_FACTOR = 0.56  # kg CO2-e/kWh, NGA Factors 2025 Table 1, published value


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


# --------------------------------------------------------------------------------------
# 1. Load real meter data
# --------------------------------------------------------------------------------------

RESIDENTIAL_COLS = {
    "grid_import": "DE_KN_residential4_grid_import",
    "grid_export": "DE_KN_residential4_grid_export",
    "pv": "DE_KN_residential4_pv",
    "sub_dishwasher": "DE_KN_residential4_dishwasher",
    "sub_freezer": "DE_KN_residential4_freezer",
    "sub_heat_pump": "DE_KN_residential4_heat_pump",
    "sub_refrigerator": "DE_KN_residential4_refrigerator",
    "sub_washing_machine": "DE_KN_residential4_washing_machine",
    "sub_ev": "DE_KN_residential4_ev",
}
INDUSTRIAL_COLS = {
    "grid_import": "DE_KN_industrial2_grid_import",
    "pv": "DE_KN_industrial2_pv",
    "storage_charge": "DE_KN_industrial2_storage_charge",
    "storage_decharge": "DE_KN_industrial2_storage_decharge",
}


def load_cumulative_meters(csv_path: Path, columns: dict[str, str], year: int) -> pd.DataFrame:
    """Load real cumulative-kWh meter columns, reindex to the full expected
    15-minute timeline, and convert to per-interval kW. Counter resets (a
    negative diff, which happens on real cumulative meters) are flagged and
    treated as missing rather than fabricated as negative power."""
    usecols = ["utc_timestamp", *columns.values()]
    frame = pd.read_csv(csv_path, usecols=usecols, parse_dates=["utc_timestamp"])
    frame = frame.rename(columns={v: k for k, v in columns.items()})
    frame = frame.set_index("utc_timestamp").sort_index()
    frame = frame[(frame.index.year == year)]
    expected = pd.date_range(f"{year}-01-01", f"{year}-12-31T23:45:00", freq="15min", tz="UTC")
    frame = frame.reindex(expected)
    frame.index.name = "timestamp"

    result = pd.DataFrame(index=frame.index)
    reset_count = 0
    for name in columns:
        cumulative = frame[name]
        delta_kwh = cumulative.diff()
        reset_mask = delta_kwh < 0
        reset_count += int(reset_mask.sum())
        delta_kwh = delta_kwh.mask(reset_mask)
        result[f"{name}_kw"] = delta_kwh / 0.25  # 15-minute interval -> kW
    result.attrs["meter_reset_count"] = reset_count
    return result


def build_residential4(year: int = 2016) -> pd.DataFrame:
    csv_path = RAW / "opsd_household" / "2020-04-15" / "household_data_15min_singleindex.csv"
    meters = load_cumulative_meters(csv_path, RESIDENTIAL_COLS, year)
    submeter_cols = [c for c in meters.columns if c.startswith("sub_")]
    df = pd.DataFrame(index=meters.index)
    # NaN propagates when either side is missing (no silent zero-fill of a missing
    # meter -- see the CN spec's "quality gate" principle: preserve gaps, flag them).
    df["grid_kw"] = meters["grid_import_kw"] - meters["grid_export_kw"]
    df["pv_kw"] = meters["pv_kw"]
    df["load_identity_kw"] = df["grid_kw"] + df["pv_kw"]  # whole-building consumption, by meter identity
    df["load_submetered_kw"] = meters[submeter_cols].sum(axis=1, min_count=1)
    df.attrs["meter_reset_count"] = meters.attrs["meter_reset_count"]
    df.attrs["raw_pv_missing"] = int(meters["pv_kw"].isna().sum())
    df.attrs["raw_grid_import_missing"] = int(meters["grid_import_kw"].isna().sum())
    return df


def build_industrial2(year: int = 2016) -> pd.DataFrame:
    csv_path = RAW / "opsd_household" / "2020-04-15" / "household_data_15min_singleindex.csv"
    meters = load_cumulative_meters(csv_path, INDUSTRIAL_COLS, year)
    df = pd.DataFrame(index=meters.index)
    df["grid_kw"] = meters["grid_import_kw"]
    df["pv_kw"] = meters["pv_kw"]
    # Real gaps must stay NaN (see build_residential4 note); a charge/discharge
    # reading of exactly 0 is a genuine "not cycling" observation, not a gap.
    df["bess_kw"] = meters["storage_decharge_kw"] - meters["storage_charge_kw"]
    df.attrs["meter_reset_count"] = meters.attrs["meter_reset_count"]
    df.attrs["raw_storage_missing"] = int(
        meters[["storage_charge_kw", "storage_decharge_kw"]].isna().all(axis=1).sum()
    )
    return df


# --------------------------------------------------------------------------------------
# 2. Load real weather and engineer features
# --------------------------------------------------------------------------------------

def load_weather(year: int = 2016) -> pd.DataFrame:
    path = RAW / "open_meteo" / "2026-08-09" / f"konstanz_{year}_weather.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    hourly = payload["hourly"]
    frame = pd.DataFrame(
        {
            "temperature_c": hourly["temperature_2m"],
            "shortwave_wm2": hourly["shortwave_radiation"],
            "direct_wm2": hourly["direct_radiation"],
            "diffuse_wm2": hourly["diffuse_radiation"],
        },
        index=pd.to_datetime(hourly["time"], utc=True),
    )
    frame.index.name = "timestamp"
    expected = pd.date_range(f"{year}-01-01", f"{year}-12-31T23:45:00", freq="15min", tz="UTC")
    return frame.reindex(expected).interpolate(limit_direction="both")


def solar_elevation_deg(index: pd.DatetimeIndex, lat: float = KONSTANZ_LAT, lon: float = KONSTANZ_LON) -> np.ndarray:
    """Approximate solar elevation (degrees) from UTC time and coordinates.
    Standard declination + hour-angle formula; ignores the equation of time
    (a few minutes of error), adequate for a feature-engineering input."""
    day_of_year = index.dayofyear.values
    utc_hour = index.hour.values + index.minute.values / 60
    declination = np.radians(23.45 * np.sin(np.radians(360 / 365 * (284 + day_of_year))))
    solar_time = utc_hour + lon / 15
    hour_angle = np.radians(15 * (solar_time - 12))
    lat_r = np.radians(lat)
    elevation = np.arcsin(
        np.sin(declination) * np.sin(lat_r) + np.cos(declination) * np.cos(lat_r) * np.cos(hour_angle)
    )
    return np.degrees(elevation)


def build_calendar_features(index: pd.DatetimeIndex) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "hour": index.hour,
            "dayofweek": index.dayofweek,
            "month": index.month,
            "is_weekend": (index.dayofweek >= 5).astype(int),
            "solar_elevation_deg": solar_elevation_deg(index),
        },
        index=index,
    )


def add_lag_and_rolling(series: pd.Series, lags: tuple[int, ...] = (4, 8, 96, 192)) -> pd.DataFrame:
    """Lags in units of 15-min intervals: 4=1h, 8=2h, 96=24h, 192=48h."""
    frame = pd.DataFrame(index=series.index)
    for lag in lags:
        frame[f"lag_{lag}"] = series.shift(lag)
    frame["roll_mean_96"] = series.shift(1).rolling(96, min_periods=48).mean()
    frame["roll_std_96"] = series.shift(1).rolling(96, min_periods=48).std()
    return frame


# --------------------------------------------------------------------------------------
# 3. Modules
# --------------------------------------------------------------------------------------

def module_data_quality(industrial: pd.DataFrame) -> dict:
    # industrial.index is already the full expected 15-minute timeline for the year
    # (see load_cumulative_meters), and bess_kw carries real NaN gaps -- pass through
    # as-is so quality_flags measures the genuine source coverage.
    flags = quality_flags(industrial["bess_kw"], expected_frequency="15min")
    missing_pct = float(flags["missing"].mean() * 100)
    frozen_intervals = int(flags["frozen"].sum())
    jump_intervals = int(flags["jump"].sum())
    return {
        "site": "industrial2 (real battery storage telemetry, 2016)",
        "expected_intervals": int(len(flags)),
        "missing_pct": round(missing_pct, 2),
        "frozen_intervals": frozen_intervals,
        "jump_intervals": jump_intervals,
        "note": "Missingness is genuine (source coverage ~68-86% for storage channels in 2016), not injected.",
    }


def module_energy_balance(residential: pd.DataFrame) -> dict:
    valid = residential.dropna(subset=["grid_kw", "pv_kw", "load_identity_kw"])
    identity_frame = pd.DataFrame(
        {
            "grid_kw": valid["grid_kw"],
            "pv_kw": valid["pv_kw"],
            "bess_kw": 0.0,
            "load_kw": valid["load_identity_kw"],
        }
    )
    identity_result = energy_balance(identity_frame, tolerance_pct=0.03)
    identity_pass_pct = float(identity_result["balance_pass"].mean() * 100)

    submetered = residential.dropna(subset=["grid_kw", "pv_kw", "load_submetered_kw"])
    submetered_frame = pd.DataFrame(
        {
            "grid_kw": submetered["grid_kw"],
            "pv_kw": submetered["pv_kw"],
            "bess_kw": 0.0,
            "load_kw": submetered["load_submetered_kw"],
        }
    )
    submetered_result = energy_balance(submetered_frame, tolerance_pct=0.03)
    submetered_pass_pct = float(submetered_result["balance_pass"].mean() * 100)
    metering_completeness_pct = float(
        (submetered["load_submetered_kw"].clip(lower=0).sum() / submetered["load_identity_kw"].clip(lower=0).sum()) * 100
    )

    return {
        "site": "residential4 (real grid/PV/appliance meters, 2016)",
        "identity_check": {
            "description": "load := grid_import - grid_export + pv (meter identity). Validates sign-convention "
            "and residual code, not independent redundant metering.",
            "intervals_evaluated": int(len(identity_result)),
            "pass_pct": round(identity_pass_pct, 2),
        },
        "submetered_check": {
            "description": "load := sum of 6 submetered appliance circuits (partial load, real submetering gap).",
            "intervals_evaluated": int(len(submetered_result)),
            "pass_pct": round(submetered_pass_pct, 2),
        },
        "metering_completeness_pct": round(metering_completeness_pct, 1),
        "meter_reset_count": residential.attrs.get("meter_reset_count", 0),
    }


def fixed_split(index: pd.DatetimeIndex, year: int = 2016):
    train = (index >= f"{year}-01-01") & (index < f"{year}-09-01")
    validate = (index >= f"{year}-09-01") & (index < f"{year}-11-01")
    test = (index >= f"{year}-11-01") & (index < f"{year+1}-01-01")
    return train, validate, test


def module_load_forecast(residential: pd.DataFrame, weather: pd.DataFrame) -> dict:
    target = (residential["grid_kw"] + residential["pv_kw"]).rename("net_load_kw")
    calendar = build_calendar_features(target.index)
    lags = add_lag_and_rolling(target)
    features = pd.concat([calendar, lags, weather[["temperature_c", "shortwave_wm2"]]], axis=1)
    frame = pd.concat([target, features], axis=1).dropna()

    train_mask, validate_mask, test_mask = fixed_split(frame.index)
    x_cols = [c for c in features.columns]
    model = QuantileForecast().fit(frame.loc[train_mask, x_cols], frame.loc[train_mask, "net_load_kw"])

    # Split-conformal (CQR) calibration: the delta is measured on the validate split
    # (01 Sep-31 Oct, disjoint from test) and only then applied to test -- see
    # core_models.conformal_interval_delta for why this stays honest.
    validate_prediction = model.predict(frame.loc[validate_mask, x_cols])
    delta_kw = conformal_interval_delta(frame.loc[validate_mask, "net_load_kw"], validate_prediction)

    raw_prediction = model.predict(frame.loc[test_mask, x_cols])
    prediction = apply_interval_delta(raw_prediction, delta_kw)
    metrics = forecast_metrics(frame.loc[test_mask, "net_load_kw"], prediction)
    raw_metrics = forecast_metrics(frame.loc[test_mask, "net_load_kw"], raw_prediction)

    return {
        "site": "residential4 net load (grid_import - grid_export + pv), 2016",
        "train_intervals": int(train_mask.sum()),
        "validate_intervals": int(validate_mask.sum()),
        "test_intervals": int(test_mask.sum()),
        "split": "train 01 Jan-31 Aug, validate 01 Sep-31 Oct (used for conformal interval "
        "calibration only, never seen by the fitted model), test 01 Nov-31 Dec -- fixed, no shuffling",
        "features": x_cols,
        "conformal_calibration": {
            "method": "split-conformal / CQR, delta measured on validate, applied to test",
            "delta_kw": round(delta_kw, 3),
            "raw_metrics_before_calibration": {k: round(v, 3) for k, v in raw_metrics.items()},
        },
        "metrics": {k: round(v, 3) for k, v in metrics.items()},
    }, frame, test_mask, prediction


HORIZONS = [(4, "1h"), (24, "6h"), (48, "12h"), (96, "24h")]


def module_horizon_forecast(residential: pd.DataFrame, weather: pd.DataFrame) -> list[dict]:
    """Real walk-forward backtest per horizon. Features are anchored at time t
    (lags/rolling stats only use information available up to t, via shift(1)
    inside add_lag_and_rolling); only the target is shifted forward by the
    horizon, so there is no leakage regardless of horizon length."""
    target = (residential["grid_kw"] + residential["pv_kw"]).rename("net_load_kw")
    calendar = build_calendar_features(target.index)
    lags = add_lag_and_rolling(target)
    features = pd.concat([calendar, lags, weather[["temperature_c", "shortwave_wm2"]]], axis=1)
    x_cols = list(features.columns)

    results = []
    for horizon_intervals, label in HORIZONS:
        future_target = target.shift(-horizon_intervals).rename("net_load_kw")
        frame = pd.concat([future_target, features], axis=1).dropna()
        train_mask, validate_mask, test_mask = fixed_split(frame.index)
        model = QuantileForecast().fit(frame.loc[train_mask, x_cols], frame.loc[train_mask, "net_load_kw"])

        # Per-horizon conformal calibration: uncertainty genuinely grows with horizon
        # (lag features go stale further out), so the interval-widening delta is
        # measured separately at each horizon on its own validate slice, then applied
        # to that horizon's test slice only. This is what closes the real 24h
        # under-coverage gap honestly, instead of just widening every horizon equally.
        validate_prediction = model.predict(frame.loc[validate_mask, x_cols])
        delta_kw = conformal_interval_delta(frame.loc[validate_mask, "net_load_kw"], validate_prediction)

        raw_prediction = model.predict(frame.loc[test_mask, x_cols])
        prediction = apply_interval_delta(raw_prediction, delta_kw)
        metrics = forecast_metrics(frame.loc[test_mask, "net_load_kw"], prediction)
        results.append(
            {
                "horizon_label": label,
                "horizon_intervals": horizon_intervals,
                "test_intervals": int(test_mask.sum()),
                "conformal_delta_kw": round(delta_kw, 3),
                **{k: round(v, 3) for k, v in metrics.items()},
            }
        )
    return results


def module_pv_evidence(residential: pd.DataFrame, weather: pd.DataFrame) -> dict:
    pv = residential["pv_kw"].clip(lower=0)
    calendar = build_calendar_features(pv.index)
    features = pd.concat(
        [calendar[["solar_elevation_deg", "hour", "month"]], weather[["temperature_c", "shortwave_wm2"]]], axis=1
    )
    frame = pd.concat([pv.rename("pv_kw"), features], axis=1).dropna()
    # Restrict the baseline to real daytime operating intervals (solar elevation > 3deg).
    # Night is deterministically zero, not a distributional tail; leaving it in the
    # training target collapses the q=0.05 quantile fit to ~0 everywhere (verified:
    # without this filter, GradientBoostingRegressor(alpha=0.05) predicts p05 ~ 0 kW
    # even at midday, because zero-inflated nights dominate the extreme-quantile loss).
    frame = frame[frame["solar_elevation_deg"] > 3]
    train_mask, _validate_mask, test_mask = fixed_split(frame.index)
    x_cols = ["solar_elevation_deg", "hour", "month", "temperature_c", "shortwave_wm2"]
    model = QuantileForecast().fit(frame.loc[train_mask, x_cols], frame.loc[train_mask, "pv_kw"])
    baseline = model.predict(frame.loc[test_mask, x_cols])

    actual = frame.loc[test_mask, "pv_kw"].copy()
    daytime_index = actual.index  # already restricted to solar_elevation_deg > 3

    # --- fault injection: 25 synthetic 2-hour daytime outages on real held-out PV output ---
    n_events = 25
    window = 8  # 8 x 15min = 2h
    candidates = [t for t in daytime_index if t + pd.Timedelta(minutes=15 * window) in actual.index]
    chosen_starts = RNG.choice(candidates, size=min(n_events, len(candidates)), replace=False)
    corrupted = actual.copy()
    injected_mask = pd.Series(False, index=actual.index)
    for start in chosen_starts:
        window_index = pd.date_range(start, periods=window, freq="15min")
        window_index = window_index.intersection(corrupted.index)
        corrupted.loc[window_index] = corrupted.loc[window_index] * 0.05  # near-total outage, not exactly zero
        injected_mask.loc[window_index] = True

    evidence = pv_underperformance(
        actual_kw=corrupted,
        expected_p50_kw=baseline.loc[corrupted.index, "p50"],
        expected_p05_kw=baseline.loc[corrupted.index, "p05"],
        interval_hours=0.25,
        persistence=4,  # 4 x 15min = 1h sustained underperformance
    )

    detected_events = 0
    for start in chosen_starts:
        window_index = pd.date_range(start, periods=window, freq="15min").intersection(evidence.index)
        if evidence.loc[window_index, "persistent"].any():
            detected_events += 1
    recall_pct = round(100 * detected_events / len(chosen_starts), 1) if len(chosen_starts) else None

    clean_daytime = injected_mask.loc[daytime_index] == False  # noqa: E712
    clean_index = daytime_index[clean_daytime.values]
    false_positive_pct = round(100 * float(evidence.loc[clean_index, "persistent"].mean()), 2)

    return {
        "site": "residential4 PV (real output), weather-adjusted baseline from real Konstanz irradiance/temperature",
        "baseline_model": "GradientBoosting quantile regression (q=0.05/0.50/0.95), features: solar elevation, "
        "hour, month, temperature, shortwave irradiance",
        "held_out_test_window": "01 Nov-31 Dec 2016 (unseen by the baseline model)",
        "fault_injection_method": f"{len(chosen_starts)} synthetic {window*15}-minute daytime outage windows "
        "(output attenuated to 5% of actual), randomly placed with a fixed seed on real held-out days",
        "known_event_recall_pct": recall_pct,
        "false_positive_rate_pct_on_clean_daytime": false_positive_pct,
        "estimated_lost_kwh_test_window": round(float(evidence["estimated_lost_kwh"].clip(lower=0).sum()), 1),
    }


def module_bess_evidence(industrial: pd.DataFrame) -> dict:
    bess = industrial["bess_kw"].dropna()
    dt_hours = 0.25
    # Data-driven usable-capacity estimate from real cycling amplitude (documented assumption).
    net_energy = (bess * dt_hours).cumsum()
    rolling_range = net_energy.rolling(96, min_periods=24).apply(lambda w: w.max() - w.min(), raw=True)
    capacity_kwh = max(float(rolling_range.quantile(0.99)), 1.0)
    soc = 50 + 100 * (net_energy - net_energy.rolling(96 * 7, min_periods=96).mean().fillna(net_energy.iloc[0])) / capacity_kwh
    soc = soc.clip(0, 100)

    train_mask, _validate_mask, test_mask = fixed_split(bess.index)
    test_bess = bess[test_mask]
    test_soc = soc.reindex(test_bess.index)

    # This is a small real behind-the-meter unit (test-window |power| p99 ~= 1.4 kW),
    # not a precinct-scale BESS -- the spec's illustrative 2 kW deadband would exclude
    # nearly all real activity. Deadband is calibrated to this site's own power range,
    # exactly as the spec requires ("允许死区...按现场计量精度...校准").
    deadband_kw = 0.2
    n_events = 40
    active = test_bess[test_bess.abs() > deadband_kw]
    chosen = RNG.choice(active.index, size=min(n_events, len(active)), replace=False)
    corrupted_soc = test_soc.copy()
    injected_mask = pd.Series(False, index=test_soc.index)
    for t in chosen:
        pos = corrupted_soc.index.get_loc(t)
        if pos + 1 >= len(corrupted_soc):
            continue
        span = corrupted_soc.index[pos : pos + 2]
        true_delta = corrupted_soc.loc[span[1]] - corrupted_soc.loc[span[0]]
        corrupted_soc.loc[span[1]] = corrupted_soc.loc[span[0]] - true_delta  # flip the sign of this interval's delta
        injected_mask.loc[span[1]] = True

    diagnosis = bess_consistency(test_bess, corrupted_soc, deadband_kw=deadband_kw)
    detected = int((diagnosis["direction_mismatch"] & injected_mask).sum())
    recall_pct = round(100 * detected / len(chosen), 1) if len(chosen) else None
    clean_mismatch_pct = round(
        100 * float(diagnosis.loc[~injected_mask, "direction_mismatch"].mean()), 2
    )

    return {
        "site": "industrial2 (real behind-the-meter battery, 2016)",
        "soc_derivation": "Indicative charge-tracking index derived from real charge/discharge telemetry and a "
        "data-driven capacity estimate (99th-percentile 24h net-throughput range = "
        f"{capacity_kwh:.1f} kWh). Not an OEM SOC signal -- OPSD does not publish one.",
        "held_out_test_window": "01 Nov-31 Dec 2016",
        "deadband_kw": deadband_kw,
        "fault_injection_method": f"{len(chosen)} synthetic single-interval sign-flip telemetry corruptions "
        f"injected into real active (>{deadband_kw}kW) charge/discharge intervals, fixed seed",
        "injected_fault_recall_pct": recall_pct,
        "false_positive_rate_pct_on_clean_intervals": clean_mismatch_pct,
    }


def classify_run_state(
    power_kw: pd.Series,
    off_threshold_kw: float = 0.05,
    run_threshold_kw: float = 0.3,
    debounce_intervals: int = 3,
) -> pd.Series:
    """Generic threshold+debounce equipment run-state classifier (OFF/IDLE/RUN,
    UNKNOWN on missing samples). Intentionally mirrors
    edge-collector-cpp/include/run_state.hpp exactly (same thresholds, same
    debounce logic) so the two independent implementations -- one on the edge in
    C++, one here for the reference backtest -- can be checked against each other.
    This is an independently designed public prototype, not Evidergy's
    confidential internal EAF-GW4 production state-recognition algorithm."""
    states: list[str] = []
    state = "UNKNOWN"
    candidate = "UNKNOWN"
    streak = 0
    for value in power_kw.to_numpy():
        if pd.isna(value):
            candidate, streak, state = "UNKNOWN", 0, "UNKNOWN"
            states.append(state)
            continue
        abs_kw = abs(float(value))
        if abs_kw >= run_threshold_kw:
            raw = "RUN"
        elif abs_kw < off_threshold_kw:
            raw = "OFF"
        else:
            raw = "IDLE"
        if raw == candidate:
            streak += 1
        else:
            candidate, streak = raw, 1
        if streak >= debounce_intervals:
            state = candidate
        states.append(state)
    return pd.Series(states, index=power_kw.index, name="run_state")


def module_edge_state_recognition(industrial: pd.DataFrame) -> dict:
    thresholds = {"off_threshold_kw": 0.05, "run_threshold_kw": 0.3, "debounce_intervals": 3}
    states = classify_run_state(industrial["bess_kw"], **thresholds)
    counts = states.value_counts()
    total = int(len(states))
    return {
        "site": "industrial2 (real behind-the-meter battery, 2016 full year)",
        "method": "Generic threshold+debounce state machine (OFF/IDLE/RUN/UNKNOWN), the identical "
        "algorithm implemented independently in edge-collector-cpp/include/run_state.hpp for the "
        "C++ edge collector -- a public prototype, not Evidergy's confidential internal EAF-GW4 "
        "production algorithm.",
        "thresholds": thresholds,
        "total_intervals": total,
        "state_distribution_pct": {state: round(100 * int(count) / total, 1) for state, count in counts.items()},
        "note": "No real labelled RUN/OFF/IDLE ground truth exists in this public dataset, so this "
        "reports real state-distribution statistics, not a recall/accuracy claim -- the same honesty "
        "constraint documented for the PV/BESS fault-injection evidence modules.",
    }


def module_bess_efficiency(industrial: pd.DataFrame) -> dict:
    """Real round-trip efficiency: total discharged energy / total charged energy,
    over every real interval with both channels present in 2016."""
    charge = industrial["bess_kw"].where(industrial["bess_kw"] < 0).abs()
    discharge = industrial["bess_kw"].where(industrial["bess_kw"] > 0)
    total_charge_kwh = float(charge.sum(skipna=True) * 0.25)
    total_discharge_kwh = float(discharge.sum(skipna=True) * 0.25)
    efficiency_pct = round(100 * total_discharge_kwh / total_charge_kwh, 1) if total_charge_kwh else None
    return {
        "site": "industrial2 (real behind-the-meter battery, 2016 full year)",
        "total_charge_kwh": round(total_charge_kwh, 1),
        "total_discharge_kwh": round(total_discharge_kwh, 1),
        "round_trip_efficiency_pct": efficiency_pct,
        "note": "Whole-year real energy totals; not adjusted for standby/idle losses outside active cycling.",
    }


def module_scope2(residential: pd.DataFrame) -> dict:
    grid_import_kwh = residential["grid_kw"].clip(lower=0) * 0.25
    monthly = grid_import_kwh.groupby(grid_import_kwh.index.month).sum()
    ledger = scope2_ledger(
        monthly, factor_kg_co2e_per_kwh=NT_DKIS_SCOPE2_FACTOR, factor_version="NGA-2025-Table1-NT-DKIS",
        data_version=DATA_VERSION,
    )
    recompute_ok = bool(np.allclose(ledger["emissions_kg_co2e"], ledger["grid_import_kwh"] * NT_DKIS_SCOPE2_FACTOR))
    return {
        "site": "residential4 real monthly grid import, 2016",
        "factor_source": "DCCEEW National Greenhouse Accounts Factors 2025, Table 1, Northern Territory "
        "(Darwin-Katherine Interconnected System), location-based",
        "factor_kg_co2e_per_kwh": NT_DKIS_SCOPE2_FACTOR,
        "months_evaluated": int(len(ledger)),
        "total_grid_import_mwh": round(float(ledger["grid_import_kwh"].sum() / 1000), 2),
        "total_emissions_tco2e": round(float(ledger["emissions_kg_co2e"].sum() / 1000), 2),
        "recompute_consistency_pct": 100.0 if recompute_ok else 0.0,
        "monthly": [
            {"month": int(m), "grid_import_kwh": round(float(v), 1), "emissions_kg_co2e": round(float(e), 1)}
            for m, v, e in zip(ledger.index, ledger["grid_import_kwh"], ledger["emissions_kg_co2e"])
        ],
    }


# --------------------------------------------------------------------------------------
# 4. Orchestration
# --------------------------------------------------------------------------------------

def main() -> None:
    print("Loading real public datasets ...")
    residential = build_residential4(2016)
    industrial = build_industrial2(2016)
    weather = load_weather(2016)

    print("Running modules ...")
    report = {
        "data_version": DATA_VERSION,
        "model_version": MODEL_VERSION,
        "generated_at_note": "generated by data_pipeline/reference_backtest.py",
        "sources": [
            {
                "id": "opsd_household_data",
                "name": "Open Power System Data - household_data (release 2020-04-15)",
                "publisher": "ISC Konstanz",
                "licence": "CC-BY 4.0",
                "url": "https://data.open-power-system-data.org/household_data/2020-04-15/",
                "file": "household_data_15min_singleindex.csv",
                "sha256": sha256_of(RAW / "opsd_household" / "2020-04-15" / "household_data_15min_singleindex.csv"),
            },
            {
                "id": "open_meteo_archive",
                "name": "Open-Meteo Historical Weather API",
                "publisher": "Open-Meteo",
                "licence": "CC-BY 4.0 (Open-Meteo terms)",
                "url": "https://archive-api.open-meteo.com/v1/archive",
                "file": "konstanz_2016_weather.json",
                "sha256": sha256_of(RAW / "open_meteo" / "2026-08-09" / "konstanz_2016_weather.json"),
            },
            {
                "id": "dcceew_nga_factors_2025",
                "name": "DCCEEW National Greenhouse Accounts Factors 2025",
                "publisher": "Australian Government (DCCEEW)",
                "licence": "Public source with attribution",
                "url": "https://www.dcceew.gov.au/climate-change/publications/national-greenhouse-accounts-factors-2025",
                "file": "national-greenhouse-account-factors-2025.xlsx",
                "sha256": sha256_of(RAW / "dcceew_nga" / "2025" / "national-greenhouse-account-factors-2025.xlsx"),
            },
        ],
        "modules": {},
    }

    report["modules"]["data_quality"] = module_data_quality(industrial)
    report["modules"]["energy_balance"] = module_energy_balance(residential)
    forecast_report, forecast_frame, test_mask, prediction = module_load_forecast(residential, weather)
    report["modules"]["load_forecast"] = forecast_report
    report["modules"]["load_forecast_by_horizon"] = module_horizon_forecast(residential, weather)
    report["modules"]["pv_evidence"] = module_pv_evidence(residential, weather)
    report["modules"]["bess_evidence"] = module_bess_evidence(industrial)
    report["modules"]["bess_efficiency"] = module_bess_efficiency(industrial)
    report["modules"]["edge_state_recognition"] = module_edge_state_recognition(industrial)
    report["modules"]["scope2"] = module_scope2(residential)

    report_path = OUT / "backtest_report.json"
    report_path.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
    print(f"Wrote {report_path}")

    # Audit extracts
    residential.to_csv(OUT / "residential4_2016_normalised.csv")
    industrial.to_csv(OUT / "industrial2_2016_normalised.csv")
    weather.to_csv(OUT / "konstanz_2016_weather_15min.csv")
    audit = forecast_frame.loc[test_mask, ["net_load_kw"]].join(prediction)
    audit.to_csv(OUT / "load_forecast_test_predictions.csv")
    print(f"Wrote audit CSVs to {OUT}")

    print(json.dumps(report["modules"], indent=2, default=str))


if __name__ == "__main__":
    main()
